services:
  hasura:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://food_user:food_password@db:5432/food_db
      HASURA_GRAPHQL_ADMIN_SECRET: your_admin_secret
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_password
      POSTGRES_DB: food_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
